receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 5s
          static_configs:
            - targets: [host.docker.internal:8000]

exporters:
  prometheus:
    endpoint: otel-collector:8889

service:
  pipelines:
    metrics:
      receivers: [ otlp, prometheus ]
      exporters: [ prometheus ]